# NOTE: This file is only for local debugging and testing (see README.md).
# It is not the actual /invocations endpoint that will be exposed during runtime.
# The actual /invocations endpoint will be generated by setuptools-docker.
# There should be no need to modify this file.
# Any custom logic needed should be consolidated in predict function.

from flask import Flask, Response, request

from model.predict import init, predict


def create_app():
    app = Flask(__name__)
    init()

    @app.route("/invocations", methods=["POST"])
    def invocations():
        return Response(predict(request.json), status=200, mimetype="application/json")

    return app
