version: "3.6"
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    network_mode: bridge
    ports:
      - 4566:4566
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - PERSISTENCE=1
      - PORT_WEB_UI=${PORT_WEB_UI- }
    volumes:
      - "s3_volume:/var/lib/localstack"
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.19.0
    container_name: mlflow
    network_mode: bridge
    ports:
      - 5000:5000
    command: [ "mlflow", "ui", "-h", "0.0.0.0" ]
volumes:
  s3_volume: